version: '3'

services:
  api:
    build:
      context: ./.docker
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    volumes:
      - ./:/usr/src/app
    entrypoint: yarn start
    container_name: jobs-api

  database:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=jobsapi123
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.database/:/var/lib/postgresql/data
    container_name: jobs-database